services:
  - type: web
    name: movie-recommender-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    pythonVersion: 3.9.6
